title = "gitleaks config"

[extend]
# useDefault extends the base configuration with the default Gitleaks rules:
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true
